### ISSUE TITLE
getOrderChance

### ISSUE THREAD

**Issue by seongyun-ko** [wonism/upbit-api-node#3]
안녕하세요
exchangeAPI 중에 getOrderChance를 쓰니까 에러가 생기는데, 한 번 확인해주실 수 있을까요

{ error:
   { message: 'Internal Server Error',
     name: 'internal_server_error' } }

**Comment by seongyun-ko** [comment]
Upbit API 설명 홈페이지에서는 암호화를 해서 질의를 날리네요
혹시 이것이?..

const request = require('request');
const uuidv4 = require("uuid/v4");
const crypto = require('crypto');
const sign = require('jsonwebtoken').sign;
const queryEncode = require("querystring").encode

const access_key = ''
const secret_key = ''

const body = {
    market: 'KRW-BTC'
}

const query = queryEncode(body)

const hash = crypto.createHash('sha512');
const queryHash = hash.update(query, 'utf-8').digest('hex');

const payload = {
    access_key: access_key,
    nonce: uuidv4(),
    query_hash: queryHash,
    query_hash_alg: 'SHA512',
};

const token = sign(payload, secret_key);

const options = {
    method: "GET",
    url: "https://api.upbit.com/v1/orders/chance?" + query,
    headers: {Authorization: `Bearer ${token}`},
    json: body
}

request(options, (error, response, body) => {
    if (error) throw new Error(error);
    console.log(body);
})

**Comment by wonism** [comment]
네, 시간 나는대로 확인해볼게요
근데 혹시 이슈 닫으신 이유는 무엇인가요?
